version: "3"

services:
  tweeter-db:
    image: postgres:9.6
    container_name: tweeter-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db
